services:


  - type: web
    name: auth-service
    env: docker
    plan: free
    rootDir: services/auth-service
    dockerfilePath: services/auth-service/Dockerfile
    envVars:
      - key: PORT
        value: 5001

  - type: web
    name: dashboard-service
    env: docker
    plan: free
    rootDir: services/dashboard-service
    dockerfilePath: services/dashboard-service/Dockerfile
    envVars:
      - key: PORT
        value: 5002
      - key: DATABASE_URL
        sync: false

  - type: web
    name: project-service
    env: docker
    plan: free
    rootDir: services/project-service
    dockerfilePath: services/project-service/Dockerfile
    envVars:
      - key: PORT
        value: 5003
      - key: DATABASE_URL
        sync: false
      - key: SUPABASE_URL
        sync: false

  - type: web
    name: api-gateway
    env: docker
    plan: free
    rootDir: api-gateway
    dockerfilePath: api-gateway/Dockerfile
    envVars:
      - key: PORT
        value: 5050
      - key: AUTH_SERVICE_URL
        sync: false
      - key: DASHBOARD_SERVICE_URL
        sync: false
      - key: PROJECT_SERVICE_URL
        sync: false
      - key: PROFILE_SERVICE_URL
        sync: false

  - type: web
    name: profile-service
    env: docker
    plan: free
    rootDir: services/profile-service
    dockerfilePath: services/profile-service/Dockerfile
    envVars:
      - key: PORT
        value: 5004
      - key: DATABASE_URL
        sync: false
